# Generated by Django 5.0.14 on 2026-04-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_type', models.CharField(choices=[('quote', 'Quote request'), ('contact', 'General contact'), ('partner', 'Partner inquiry'), ('newsletter', 'Newsletter signup')], default='contact', max_length=32)),
                ('name', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('service', models.CharField(blank=True, max_length=160)),
                ('message', models.TextField(blank=True)),
                ('source_path', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
